### ISSUE TITLE
webapp jsp架构升级到vue.js中...

### ISSUE THREAD

**Issue by krislorem** [ZhaiJinPei/bookshop-javaweb#3]
- [x] jsp+servlet+filter+listener 
- [ ] vue.js 3 + vite + pnpm + ts + axios + element-ui plus

**Comment by ZhaiJinPei** [comment]
@happypeter

**Comment by krislorem** [comment]
@Yeluzii 困🙌，就多熬。🙌熬不起🙌，就别困。🙌代码是代码，环境是环境。🙌你要是一直拿代码当环境，哥们儿，你怎么不去记事本写啊？🙌

**Comment by krislorem** [comment]
妈的，没时间了，就这样，不搞了
